[package]
name = "atom-backend"
version.workspace = true
edition.workspace = true

[[bin]]
name = "atom-compile"
path = "src/main.rs"

[dependencies]
atom-ast = { path = "../atom-ast" }
cranelift = "0.114"
cranelift-module = "0.114"
cranelift-jit = "0.114"
cranelift-object = "0.114"
cranelift-native = "0.114"
target-lexicon = "0.12"

[dev-dependencies]
